### ISSUE TITLE
question

### ISSUE THREAD

**Issue by iofirag** [zpdove/08b42fa888cf6b513d4d27a3dc2e5ca5#1]
In software -stage 3:
is your suspects.json is the final suspected list?
because i sort this list by ip sorting, and it's not compleate the stage.. :/

**Comment by zpdove** [comment]
The hint is that all the suspects can be seen using the same ip addresses via shared vpn or public location. I don't really support the idea of sharing answers directly but it seems it has already been leaked. So might as well give some insight.

I used mongodb, and if you query the hints and the ip's used by the suspects:
query: { "uid": { $nin: [435, 2211, 2449, 3538, 3608, 4024, 5206, 6796, 7239, 9237] }, "uip": { $in: ['10.192.20.173', '41.239.144.6', '42.74.74.110', '51.70.255.188', '58.149.209.97', '67.141.120.237', '68.17.81.83', '78.12.11.167', '103.205.114.34', '104.45.191.227', '109.242.247.39', '114.79.247.223', '124.9.188.155', '127.95.83.100', '130.76.88.3', '138.27.249.121', '139.210.78.22', '143.204.212.207', '162.219.33.114', '211.104.116.62', '230.167.210.226'] } }

you will obtain a list of possible suspects that also used the same ip:
87, 1808, 4918, 5590, 5630, 5772, 6529, 7051, 7159, 9091, 9482

now go through and analyze each of the possible subjects till you can see matches. Some people used the dates between when the earliest known suspect and the last known suspect and plotted if they were within the time period which did get them the same answer. I used clustering on the urls which gave me more insight into activities and finding out more in detail the suspects behaviors, what they like, and how they use the internet via their url requests. They were all students more or less that liked football / soccer and had a prime interest in math and physics, some were indian, and I could go on and on...

There are only three additional suspects (within that list of possibles) to place and sorting these by ip is ez pz and doesnt really require programming as I initially thought, thinking it was going to be a big list.

I updated the post with the real answer as well on the page if you don't like doing the effort.

- Best of Luck
